---
Name: innoweb-default-home
---

---
Name: innoweb-default-home-multi
Only:
  moduleexists: 'symbiote/silverstripe-multisites'
---
Symbiote\Multisites\Model\Site:
  extensions:
    - Innoweb\DefaultHome\Extensions\DefaultHomeSiteExtension

---
Name: innoweb-default-home-configured-multi
Only:
  moduleexists: 'fromholdio/silverstripe-configured-multisites'
---
Symbiote\Multisites\Model\Site:
  extensions:
    - Innoweb\DefaultHome\Extensions\DefaultHomeSiteExtension

---
Name: innoweb-default-home-nomulti
Except:
  moduleexists:
    - 'symbiote/silverstripe-multisites'
    - 'fromholdio/silverstripe-configured-multisites'
---
SilverStripe\CMS\Model\SiteTree:
  extensions:
    - Innoweb\DefaultHome\Extensions\DefaultHomeSiteTreeExtension
